version: '3.3'
services:
  web:
    build: ./client
    depends_on:
      - server
    ports:
      - "80:80"
    environment:
      - SERVER_HOST="localhost"
      - SERVER_PORT="3000"

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - SERVER_HOST=localhost
      - SERVER_PORT=3000
